// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTq3c34B3SL1tMg8hKK0_tDoHS9u9ySwc',
    appId: '1:353912972276:web:dc21a00ec4b948282b0fa1',
    messagingSenderId: '353912972276',
    projectId: 'deep-project-3',
    authDomain: 'deep-project-3.firebaseapp.com',
    storageBucket: 'deep-project-3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjyPdXJRMFALM3fm4dQyuxzX6myn96_4',
    appId: '1:353912972276:android:fbd1fdbc839274462b0fa1',
    messagingSenderId: '353912972276',
    projectId: 'deep-project-3',
    storageBucket: 'deep-project-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0UFNlAz6v9vqU83DdZiut7GP9D4Ol2Oc',
    appId: '1:353912972276:ios:82f23dce6685a3f22b0fa1',
    messagingSenderId: '353912972276',
    projectId: 'deep-project-3',
    storageBucket: 'deep-project-3.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0UFNlAz6v9vqU83DdZiut7GP9D4Ol2Oc',
    appId: '1:353912972276:ios:82f23dce6685a3f22b0fa1',
    messagingSenderId: '353912972276',
    projectId: 'deep-project-3',
    storageBucket: 'deep-project-3.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTq3c34B3SL1tMg8hKK0_tDoHS9u9ySwc',
    appId: '1:353912972276:web:de62c3e4ccd9507a2b0fa1',
    messagingSenderId: '353912972276',
    projectId: 'deep-project-3',
    authDomain: 'deep-project-3.firebaseapp.com',
    storageBucket: 'deep-project-3.appspot.com',
  );

}